Aiax 20 firebase initial config
kheironCo/AIAX-client pull request #13
Opened 2024-06-30 00:13 UTC by gastonjau

Video en Slack

2024-07-02 19:46 UTC, MarcosRehtanz requested changes

2024-07-02 19:46 UTC, MarcosRehtanz commented on src/config/firebase.js
Pasar este archivo con la extension`.ts`

2024-07-02 19:46 UTC, MarcosRehtanz commented on src/pages/Register/index.tsx
> +  const navigate = useNavigate();
Los hooks deben ir al principio del componente
- `hooks`
- `functions`
- `useEffect`

2024-07-02 19:49 UTC, MarcosRehtanz requested changes

2024-07-02 19:49 UTC, MarcosRehtanz commented on src/pages/Login/index.tsx
Faltó incorporar el validador de formularios con `React-Hook-Form` y crear el Schema del login

2024-07-03 15:38 UTC, gastonjau commented
![image](https://github.com/kheironCo/AIAX-client/assets/132623094/8ffc54ec-6b44-4a84-83c4-d4d46f1bad61)

2024-07-03 16:46 UTC, MarcosRehtanz approved these changes

2024-07-03 16:49 UTC, merged