Aiax 41 create new contact form
kheironCo/AIAX-client pull request #19
Opened 2024-07-12 16:15 UTC by gastonjau

2024-07-14 15:21 UTC, gastonjau commented
![image](https://github.com/user-attachments/assets/5af43f60-11c9-45bb-ab89-51dcd02a61f7)

2024-07-15 19:11 UTC, MarcosRehtanz commented on src/schema/User/index.ts
> -  });
Por qué se eliminó esta validación de contraseña?

2024-07-15 19:13 UTC, MarcosRehtanz requested changes

2024-07-15 19:13 UTC, MarcosRehtanz commented on src/schema/User/index.ts
>  export type IUserRegister = z.infer<typeof UserRegister>;
El type debe de estar debajo de su respectivo esquema

2024-07-15 19:13 UTC, MarcosRehtanz commented on src/schema/User/index.ts
> +export type IContactForm = z.infer<typeof ContactForm>;
Esto debe de estar una carpeta Contact. `schema/Contact`
No se deben de mesclar los esquemas

2024-07-16 18:52 UTC, MarcosRehtanz approved these changes

2024-07-16 18:54 UTC, merged