create-login-page
kheironCo/AIAX-client pull request #9
Opened 2024-06-17 20:53 UTC by gastonjau

![image](https://github.com/kheironCo/AIAX-client/assets/132623094/b55a7128-d5bf-449e-a1e5-837e80140810)

2024-06-17 23:10 UTC, gastonjau commented
![image](https://github.com/kheironCo/AIAX-client/assets/132623094/fa1fcc73-14f3-4e64-84c7-e5427b4b5be4)

2024-06-18 19:47 UTC, MarcosRehtanz requested changes

2024-06-18 19:47 UTC, MarcosRehtanz commented on src/pages/landing/components/NavBar/index.tsx
> +            <ButtonKUI palette="gold" onClick={navegar}>
los nombres en ingles y que sean descriptivos sobre su funcionalidad

2024-06-18 19:47 UTC, MarcosRehtanz commented on src/pages/Login/index.tsx
> +import imagenLlave from 'assets/imgs/imagenLlave.png';
nombres en ingles

2024-06-19 22:41 UTC, merged